[project]
name = "my-trading-bot"
version = "0.1.0"
requires-python = ">=3.11,<3.14"
dependencies = [
    "fastapi",
    "pandas",
    "pandas-ta",
    "plotly",
    "pydantic-settings",
    "pymongo",
    "python-telegram-bot",
    "pytz",
    "uvicorn",
    "MetaTrader5; sys_platform == 'win32'",
]
